version: '3.8'
services:
  app:
    build: .
    ports:
      - "4545:4545"  # Изменим порт на тот, что вы указали в application.properties
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bnk
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: madiksadik2015
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_APPLICATION_NAME: bank-services
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: bnk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: madiksadik2015
    ports:
      - "5432:5432"
